version: "3.0"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/pgdata/
      - POSTGRES_DB=studydb
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - .:/src/
      - static:/static
      - media:/media
    depends_on:
      - db
    environment:
        DJANGO_SETTINGS_MODULE: 'settings.dev'
        PY_AUTORELOAD: 1
    command: /bin/bash -c 'pip install -r requirements.txt && invoke run'


  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static:ro
      - media:/media
    links:
      - web
    ports:
      - 8000:80

volumes:
  pgdata: { }
  static: { }
  media: { }
