# Generated by Django 4.0.4 on 2022-10-28 16:15

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.authentication.models.UserManager()),
            ],
        ),
    ]
